// <auto-generated />
using System;
using EventHub_EFCore_Assingnment2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventHub_EFCore_Assingnment2.Migrations
{
    [DbContext(typeof(EventHubDbContext))]
    [Migration("20260424144229_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventHub_EFCore_Assingnment2.Models.Attendee", b =>
                {
                    b.Property<int>("AttendeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendeeId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttendeeId");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("EventHub_EFCore_Assingnment2.Models.Badge", b =>
                {
                    b.Property<int>("BadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BadgeId"));

                    b.Property<int>("AttendeeId")
                        .HasColumnType("int");

                    b.Property<string>("BadgeNumber")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("Varchar(20)");

                    b.HasKey("BadgeId");

                    b.HasIndex("AttendeeId")
                        .IsUnique();

                    b.ToTable("Badge");
                });

            modelBuilder.Entity("EventHub_EFCore_Assingnment2.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("Varchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxAttendees")
                        .HasColumnType("int");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentEventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("Varchar(200)");

                    b.HasKey("EventId");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("ParentEventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EventHub_EFCore_Assingnment2.Models.Organizer", b =>
                {
                    b.Property<int>("OrganizerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizerId"));

                    b.Property<string>("CompanyName")
                        .HasMaxLength(150)
                        .HasColumnType("Varchar");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("Varchar");

                    b.HasKey("OrganizerId");

                    b.ToTable("Organizers");
                });

            modelBuilder.Entity("EventHub_EFCore_Assingnment2.Models.OrganizerProfile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("Varchar(500)");

                    b.Property<string>("LogoPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("Varchar(255)");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("ProfileId");

                    b.HasIndex("OrganizerId")
                        .IsUnique();

                    b.ToTable("OrganizerProfile");
                });

            modelBuilder.Entity("EventHub_EFCore_Assingnment2.Models.Registration", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("AttendeeId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("Varchar(500)");

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("EventId", "AttendeeId");

                    b.HasIndex("AttendeeId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("EventHub_EFCore_Assingnment2.Models.Attendee", b =>
                {
                    b.OwnsOne("EventHub_EFCore_Assingnment2.Models.Address", "HomeAddress", b1 =>
                        {
                            b1.Property<int>("AttendeeId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("Varchar(100)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("Varchar(100)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("Varchar(20)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("Varchar(200)");

                            b1.HasKey("AttendeeId");

                            b1.ToTable("Attendees");

                            b1.WithOwner()
                                .HasForeignKey("AttendeeId");
                        });

                    b.Navigation("HomeAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("EventHub_EFCore_Assingnment2.Models.Badge", b =>
                {
                    b.HasOne("EventHub_EFCore_Assingnment2.Models.Attendee", "Attendee")
                        .WithOne("Badge")
                        .HasForeignKey("EventHub_EFCore_Assingnment2.Models.Badge", "AttendeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendee");
                });

            modelBuilder.Entity("EventHub_EFCore_Assingnment2.Models.Event", b =>
                {
                    b.HasOne("EventHub_EFCore_Assingnment2.Models.Organizer", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventHub_EFCore_Assingnment2.Models.Event", "ParentEvent")
                        .WithMany()
                        .HasForeignKey("ParentEventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Organizer");

                    b.Navigation("ParentEvent");
                });

            modelBuilder.Entity("EventHub_EFCore_Assingnment2.Models.OrganizerProfile", b =>
                {
                    b.HasOne("EventHub_EFCore_Assingnment2.Models.Organizer", "Organizer")
                        .WithOne("Profile")
                        .HasForeignKey("EventHub_EFCore_Assingnment2.Models.OrganizerProfile", "OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("EventHub_EFCore_Assingnment2.Models.Registration", b =>
                {
                    b.HasOne("EventHub_EFCore_Assingnment2.Models.Attendee", "Attendee")
                        .WithMany()
                        .HasForeignKey("AttendeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventHub_EFCore_Assingnment2.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendee");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventHub_EFCore_Assingnment2.Models.Attendee", b =>
                {
                    b.Navigation("Badge")
                        .IsRequired();
                });

            modelBuilder.Entity("EventHub_EFCore_Assingnment2.Models.Organizer", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
